---
title: Choosing Epidemiological Journals
author: 
  - Ehsan Karim
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  bookdown::html_document2:
    citation_package: natbib
    toc: true
    df_print: paged
    fig_caption: yes
    highlight: textmate
    keep_md: yes
    number_sections: yes
    theme: lumen
  html_document:
    df_print: paged
    toc: true
    citation_package: natbib
    fig_caption: yes
    number_sections: yes
  pdf_document:
    citation_package: natbib
    toc: true
    fig_caption: yes
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
  word_document: default
always_allow_html: yes
link-citations: yes
fontsize: 12pt
geometry: margin=1in
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos='H')
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60), tidy=TRUE)

```

\pagenumbering{arabic}

You can find more information about choosing a peer-reviewed journal (in general) in this [site](https://ehsanx.github.io/Scientific-Writing-for-Health-Research/finding-suitable-journals.html).

> **_Disclaimer:_** 
(1) This page is created for personal usage; may not be the most updated; please check the up-to-date instructions from the respective journal sites (links added at the time of the last update; feel free to report broken links). 
(2) The journals are not listed in any particular order. 
(3) See the instruction links for added descriptions. Some of the descriptions are copied from the instruction pages as is (some journals provide their own summary, e.g., PDS). 
(4) Some of these journals are associated with very high [APC](https://en.wikipedia.org/wiki/Article_processing_charge) / open access (or page charge, or color charge) fees; please consult your institution if they have any discount / agreement with journals / publishers (e.g., here is an [example](https://scholcomm.ubc.ca/open-access-publisher-discounts/)). 
(5) Please check on your own if any of these are [predatory journals](https://en.wikipedia.org/wiki/Predatory_publishing) or not (e.g., see [Beall's List](https://beallslist.net/), [Stefan and Helgesson, 2018](https://onlinelibrary.wiley.com/doi/full/10.1002/leap.1135) or [Grudniewicz et al., 2019](https://www.nature.com/articles/d41586-019-03759-y)). 


# General Epidemiology Journals

## International Journal of Epidemiology / IJE {-}

[Instructions link here](https://academic.oup.com/ije/pages/General_Instructions)

|     Type                             |     Words (excluding refs/key features)                                                             |     Tab or Fig (total)    |     Ref    |     Abstract words                                                |     Key message bullet points (in complete sentence)    |     Max authors    |
|--|---|-|-|--|--|-|
|     Original Articles                |     3000                                                                                            |     8                     |     50     |     250                                                           |     3-5                                                 |                    |
|     Cohort Profiles                  |     2500-3000                                                                                       |     5                     |     30     |                                                                   |     3-5                                                 |                    |
|     Cohort Profile Updates           |     2000-2500                                                                                       |     5                     |     30     |                                                                   |     3-5                                                 |                    |
|     Data Resource Profiles           |     2500-3000                                                                                       |     5                     |     30     |                                                                   |     3-5                                                 |                    |
|     Software Application Profiles    |     1500-2000 (include case use)                                                                    |     2                     |     25     |     150 with URL                                                  |                                                         |                    |
|     Education Corner                 |     1500-2500 (supplementary additional; should include an illustration or motivating   example)    |     5                     |     30     |     Unstructured, 250                                             |     3-5                                                 |                    |
|     Opinion                          |     3000                                                                                            |     4                     |     30     |     Unstructured, 150 (only for editors/will not be published)    |                                                         |                    |
|     Letters to the Editor            |     700 (or 500 for response)                                                                       |     2                     |     10     |                                                                   |                                                         |     3              |
|     Editorials (invited only)        |     1500                                                                                            |     2                     |     20     |                                                                   |                                                         |     4              |
|     Commentaries (invited only)      |     1000                                                                                            |     2                     |     10     |                                                                   |                                                         |     4              |
|     Book Reviews                     |     500-1500;   usually commissioned but we may consider uninvited submissions                      |                           |            |                                                                   |                                                         |                    |
|     Obituaries                       |     500-1000   + high-quality image of the person                                                   |                           |            |                                                                   |                                                         |                    |
|     Poetry                           |     usually   commissioned but we will consider uninvited submissions                               |                           |            |                                                                   |                                                         |                    |

## Epidemiology / EPI {-}

[Instructions link here](https://edmgr.ovid.com/epid/accounts/ifauth.htm)

|Type|Words and refs|     Description|
|--|--|--------|
|     Original Research Articles           |     1500 to 4000 words                                  |     Research articles should begin with a short introduction (background   and reason for undertaking the work), followed by Methods, Results, and   Discussion. Papers on methodology are not required to follow this structure.                                                                                                                  |
|     Brief Reports                        |     up to 1500 words                                    |     brief reports of research results or methodological developments that   can be presented succinctly. Brief reports should follow the content and   structure of original research articles.                                                                                                                                                    |
|     Validation Studies                   |     2000 words                                          |     Validation studies should follow the outline for an Original Research   Article and should provide estimates to inform bias analyses or otherwise be   of use in epidemiologic research.                                                                                                                                                       |
|     Review Articles and Meta-analyses    |     up to 5000 words                                    |                                                                                                                                                                                                                                                                                                                                                    |
|     Commentaries                         |     up to 2000 words                                    |     Commentaries may address any topic of interest to the epidemiologic   community, including the implications of specific findings for public health   policy or descriptions of novel hypotheses with strong plausibility.                                                                                                                      |
|     Letters                              |     up to 400 words, 4 references                       |     Letters allow authors to submit critical responses to published   papers. Letters are published only online, but will be listed in the   corresponding issue's table of contents and indexed in PubMed.                                                                                                                                        |
|     Research Letters                     |     up to 600 words, 1 table or figure, 8 references    |     Research letters allow authors to present original data in a succinct   format. Like Original Research Articles or Brief Reports, these manuscripts   are subject to peer review. Letters are published only online, where they are   available for free. They will be listed in the table of contents of an issue   and indexed in PubMed.    |
|     Remembrances                         |     up to 400 words, with photograph                    |                                                                                                                                                                                                                                                                                                                                                    |               |


## American Journal of Epidemiology / AJE {-}

[Instructions link here](https://academic.oup.com/aje/pages/Instructions_To_Authors)

| Manuscript Type| Description| Word Count | Abstract? |
| --| -------| - | - |
|                                                  | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |            |           |
| Original Contribution                            | Reports of original research comprising laboratory, field, clinical, or mathematical modeling studies of conditions that impact the population's health, as well as studies of statistical or methodological issues.  | 4,000      | Yes       |
| Practice of Epidemiology and Methodology         | Papers dealing with the practical application of epidemiologic or statistical methods (such as the implementation of statistical techniques or the evaluation of interview strategies).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | 4,000      | Yes       |
| Study Design                                     | Manuscripts that describe designs, methods, and procedures of specific epidemiologic studies, particularly large and/or multicenter studies.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 4,000      | Yes       |
| Systematic Reviews and Meta- and Pooled Analysis | In-depth reviews and analyses on both substantive subject areas and methodologic aspects of epidemiology.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | 4,000      | Yes       |
| The AJE Classroom                                | Short articles in which basics of epidemiologic methods are explained.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1,500      | No        |
| Research Letter                                  | Articles presenting new data (often preliminary) that are not of sufficient length to warrant an Original Contribution. Only 1 figure and 1 short table are permitted.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 1,500      | No        |
|                                                  | OPINION ARTICLES                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |            |           |
| Commentary                                       | Opinion piece about either an epidemiologic topic or a previously published AJE article.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | 2,000      | Yes       |
| Data-Driven Commentary                           | Article in which authors present the state of knowledge on a topic along with their opinions on the topic. The purpose is to effectively synthesize the available data while also commenting on the current state of affairs                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 4,000      | Yes       |
| Point–Counterpoint                               | Groups of 2 articles in which authors present different sides of a discussion.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | 2,000 each | Yes       |
| Editorial                                        | A short opinion piece written by an editor/editors of the AJE. Similar articles written by those who are not editors should be submitted as commentaries.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | 1,500      | No        |
| Letter to the Editor                             | Brief response to an article recently published in the AJE. The authors of the original paper will be invited to respond. Note that letters to the editor are not blinded.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | 500–600    | No        |
| Erratum                                          | A brief article detailing necessary corrections to a previously published AJE article. They must include a description of the error, the corrected text, and a reference to the original article.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | No limit   | No        |


## Journal of Clinical Epidemiology / JCE {-}

[Instructions link here](https://www.elsevier.com/journals/journal-of-clinical-epidemiology/0895-4356/guide-for-authors)

Abstract headings: Objective, Study Design and Setting, Results, and Conclusion

|     Type                 |     Word count     |     Abstract      |     References       |     Table        |     Figure       |
|--------------------------|--------------------|-------------------|----------------------|------------------|------------------|
|     Reviews              |     3,000 words    |     200 words     |     50 references    |     5 tables     |     5 figures    |
|     Original Articles    |     3,000 words    |     200 words     |     50 references    |     5 tables     |     5 figures    |
|     Letters              |     500 words      |     200 words     |                      |                  |                  |
|     Commentaries         |     2,500 words    |     200 words     |     10 references    |     2 figures    |     2 tables     |

## Pharmacoepidemiology and Drug Safety / PDS {-}

[Instructions link here](https://onlinelibrary.wiley.com/page/journal/10991557/homepage/forauthors.html)


| Article Type|   Description|Word Limit|   Abstract / Structure|Other Requirements|
|--|-----|-----|--|---|
| Original Articles                                          | Reports of new research findings or conceptual analyses that make a significant contribution to knowledge                                                                                                        | 3,000 limit (excluding abstract, tables, figures, and references), Structure: Purpose, Methods, Results, and Conclusions                                                                                                                                      | Yes, structured, no more than 250 words                 | Five Key Points Plain Language Summary Ethics / IRB Statement Conflicts of Interest Statement |
| Commentaries                                               | Commentaries are evidence-based opinion pieces that cover a variety of topics of current interest in pharmacoepidemiology and pharmacovigilance, and the intersection between these disciplines and society.     | 1,500 limit (commissioned and submitted); no more than 15 references                                                                                                                                                                                          | No abstract                                             | Five Key Points                                                                               |
| Review Articles                                            | Critical reviews of the literature, including systematic reviews and meta-analyses. Hot topics, controversies, and pharmacoepidemiologic methods are welcome.                                                    | 3,000 limit (excluding abstract, figures, tables and references); no more than 150 references                                                                                                                                                                 | Yes, unstructured                                       | Five Key Points                                                                               |
| Brief Reports                                              | Preliminary findings of research in progress or a case report of particular interest                                                                                                                             | 1,500 limit, Structure: Purpose, Methods, Results, and Conclusions; No more than 1 table, 1 figure, 15 references. In highly unusual situations, case reports (Pharmacoepidemiol Drug Saf 2007; 16 :473), will be considered for publication as Brief Reports | Yes, structured (Purpose, Methods, Results, Conclusions | Five Key Points Ethics / IRB Statement Conflicts of Interest Statement                        |
| Letters to the Editor                                      | May be in response to issues arising from recently published articles, or short, free-standing opinion pieces.                                                                                                   | 1,000 limit, unstructured                                                                                                                                                                                                                                     | No abstract                                             |                                                                                               |
| Real-World Data Sources for Pharmacoepidemiologic Research | Dedicated to describing available real-world data sources for pharmacoepidemiologic studies. | 3000 limit (excluding abstract, tables, figures, and references); unstructured.                                                                                                                                                                               | Yes, unstructured, no more than 250 words               | Five Key Points See FAQs here for the core contents to cover.                                 |



## European Journal of Epidemiology / EJE {-}

[Instructions link here](https://www.springer.com/journal/10654/submission-guidelines)


| Article Type|   Description|Word Limit|   
|--|-----|-----|--|
| Original Articles|   provide 4 to 6 keywords which can be used for indexing purposes. |An abstract of 150 to 250 words. The abstract should not contain any undefined abbreviations or unspecified references.|   
| Reviews|   Solicited and non-solicited papers on topical subjects will be published.||   
| Short Communications|  Be very concise in writing their introduction and discussion.|The length and the number of figures are limited to 2000 words (text, including 10 references), 2 figures (which can be multi-panel figures) and a maximum of two tables. |   
| Commentaries |   Solicited and non-solicited papers on topical subjects will be published.||
| Letters to the Editor |   |The length is limited to a maximum of 1000 words and 5 references.|   

## Annals of Epidemiology / AoE {-}

[Instructions link here](https://www.sciencedirect.com/journal/annals-of-epidemiology)


|     Types of paper              |     words                                                                         |     structured abstract     |     Tables, Figures, or other     |     Description                                                                                                                                                                                                                                                                                                               |
|----|---|---|---|----------------|
|     Original   article          |     3000                                                                          |     200                     |     6                                                     |     a new piece of work                                                                                                                                                                                                                                                                                                       |
|     Brief Communication         |     2000                                                                          |     200                     |     3                                                     |     a short Original Article                                                                                                                                                                                                                                                                                                  |
|     Rapid Reports               |     1000                                                                          |                             |                                                           |     a new fact, method, observation for quick   presentation                                                                                                                                                                                                                                                                  |
|     Study Method and Design     |                                                                                   |                             |                                                           |     methodologic, logistic, or design focus that   may or may not contain results but that presents something of interest in the   design itself; simple descriptions of newly established studies, without   results or an issue of intrinsic interest, are discouraged—format the same as   that for original articles.     |
|     Reviews and Commentaries    |     negotiable, 5000                                                              |     200, unstructured       |     as needed                                             |     descriptive, analytic or synthetic   consideration of a topic or hypothesis                                                                                                                                                                                                                                               |
|     Editorials                  |     1500; generally invited but   could be author initiated after consultation    |                             |                                                           |     a comment on a paper that has appeared   recently in the Annals                                                                                                                                                                                                                                                           |
|     Letters to the Editor       |     750                                                                           |     Not allowed             |                                                           |                                                                                                                                                                                                                                                                                                                               |
|     Book Reviews                |     1500; generally invited                                                       |                             |                                                           |                                                                                                                                                                                                                                                                                                                               |


## Biostatistics & Epidemiology / BE {-}

[Instructions link here](https://www.tandfonline.com/action/authorSubmission?show=instructions&journalCode=tbep20)

|     Type                   |     Word count                    |     Abstract                                |     Keywords    |
|----------------------------|-----------------------------------|---------------------------------------------|-----------------|
|     research   articles    |     There   are no word limits    |     unstructured   abstract of 200 words    |     5           |
|     review   articles      |     There   are no word limits    |     unstructured   abstract of 200 words    |     5           |


# Epidemiology of some specific topics


## Epidemiology & Infection / EI {-}

[Instructions link here](https://www.cambridge.org/core/journals/epidemiology-and-infection/information/author-instructions)

outline key results / importance in 3-5 short bullet points

|     Type                       |     Word count                                                         |     Abstract                    |     References             |     Table Figure                         |
|--------------------------------|------------------------------------------------------------------------|---------------------------------|----------------------------|------------------------------------------|
|     Original   Papers          |     preferably between 2000 and 4000 words (excluding   references)    |                                 |     below 40               |                                          |
|     Short   Reports            |      below 3000 (excluding references)                                 |                                 |     up to 10 references    |     not more than one table or figure    |
|     Review   Articles          |     between 2500 and 4000 words                                        |                                 |                            |     no limit to tables and figures       |
|     From the   Field           |     up to 2000 words                                                   |     no longer than 100 words    |     maximum of 15          |                                          |
|     For Debate                 |                                                                        |                                 |                            |                                          |
|     Letters to   the Editor    |                                                                        |                                 |                            |                                          |


## Infection Control & Hospital Epidemiology / ICHE {-}

[Instructions link here](https://www.cambridge.org/core/journals/infection-control-and-hospital-epidemiology/information/author-instructions)

|     Type                              |     abstract                                         |     word count                     |     Table or Figures                     |     References                    |
|---------------------------------------|------------------------------------------------------|------------------------------------|------------------------------------------|-----------------------------------|
|     Original Articles                 |     structured abstract of no more than 250 words    |     3,000 words                    |     no more than 7 tables and figures    |     no more than 40 references    |
|     Concise Communications            |     narrative abstract of no more than 50 words      |     no more than 1,200 words       |     no more than 2 tables or figures     |     no more than 10 references    |
|     Research Briefs                   |                                                      |     no more than 900 words         |     no more than 1 table or figure       |     no more than 10 references    |
|     Letters to the Editor             |                                                      |     should not exceed 900 words    |     no more than 1 table or figure       |     no more than 10 references    |
|     Invited Reviews                   |                                                      |                                    |                                          |                                   |
|     Commentaries (invitation only)    |                                                      |                                    |                                          |                                   |

## Global Epidemiology / GE {-}

[Instructions link here](https://www.elsevier.com/journals/global-epidemiology/2590-1133/guide-for-authors)

Follows instructions established by the [Uniform Requirements for Manuscripts Submitted to a Biomedical Journal](http://www.icmje.org/recommendations/).

|     Type                                                        |     Description                                                                                                                                                                              |          |
|-----------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------|
|     Original Research   Articles                                |     (including   reports of null results)                                                                                                                                                    |          |
|     Review Articles                                             |                                                                                                                                                                                              |          |
|     Reports of   methodological developments and innovations    |     highest priority to those that focus on the concepts, ideas and   philosophical foundations of epidemiologic methods.                                                                    |          |
|     Study Protocols                                             |     In-depth descriptions of methods to be used in soon-to-be-launched   epidemiological studies.                                                                                            |          |
|     Teaching articles                                           |     up-to-date discussions of epidemiologic methods and practices, that   achieve excellence in explanation, and that are suitable for use in the   classroom or for continuing education    |          |
|     Validation Studies                                          |     inform quantitative bias (uncertainty, sensitivity) analyses.                                                                                                                            |          |
|     Commentaries (usually   invited)                            |                                                                                                                                                                                              |          |
|     Editorials (usually   invited)                              |                                                                                                                                                                                              |          |
|     Letters to the Editor                                       |                                                                                                                                                                                              |          |
|     International   Perspectives                                |     Commentaries on public health issues around the world, especially in   developing countries.                                                                                             |          |


## Clinical Epidemiology and Global Health / CEGH {-}

[Instructions link here](https://www.sciencedirect.com/journal/clinical-epidemiology-and-global-health)

|     Type                           |     Word count                                               |     References       |     Table or Fig                    |     Abstract      |     Keywords    |
|------------------------------------|--------------------------------------------------------------|----------------------|-------------------------------------|-------------------|-----------------|
|     Original Research Articles     |     not exceed 3000 words, but not less   than 2500 words    |     30 references    |     up to 2 tables and 4 Figures    |     250 words     |     5           |
|     Editorials (solicited)         |     1200 words                                               |     10 references    |     Upto 1 figure and 1 table       |                   |                 |
|     Review                         |     3500 - 4000                                              |     40               |     up to 4 tables and 3 Figures    |     structured    |     6           |
|     Evidence updates               |                                                              |                      |                                     |                   |                 |
|     Information and Commentary     |     500 words                                                |     5                |     Upto 1 figure and 2 table       |     structured    |     5           |
|     Letters to the Editor          |     500 words                                                |     3                |     Upto 1 figure and 1 table       |                   |                 |


## Journal of Epidemiology and Global Health / JEGH {-}

[Instructions link here](https://www.springer.com/journal/44197/submission-guidelines)

|     Type                    |     Abstract            |     Keywords           |     Format         |
|-----------------------------|-------------------------|------------------------|--------------------|
|     Research Article        |     150 to 250 words    |     4 to 6 keywords    |     Word/ LaTeX    |
|     Review                  |                         |                        |                    |
|     Perspective             |                         |                        |                    |
|     Letter to the Editor    |                         |                        |                    |
|     Commentary              |                         |                        |                    |

## Epidemiology and Psychiatric Sciences / EPS {-}

[Instructions link here](https://www.cambridge.org/core/journals/epidemiology-and-psychiatric-sciences/information/author-instructions)

|     Type                            |     Word count    |     Abstract                                |     Tables or Figures                                               |     Keywords    |
|-------------------------------------|-------------------|---------------------------------------------|---------------------------------------------------------------------|-----------------|
|     Original articles               |     4000 words    |     Structured, 400 words                   |     no more than a combined total of six tables and/or figures      |     4           |
|     Editorials                      |     3000 words    |     non-structured abstract of 300 words    |                                                                     |                 |
|     Special Articles                |     4000 words    |     Structured, 400 words                   |     no more than a combined total of six tables and/or figures      |                 |
|     Commentaries                    |     1500 words    |     without an abstract                     |                                                                     |                 |
|     Methodological Contributions    |     4000 words    |     structured abstract of 400 words        |     no more than a combined total of seven tables and/or figures    |     4           |
|     Systematic Reviews              |     4000 words    |     structured abstract of 400 words        |     no more than a combined total of seven tables and/or figures    |     4           |
|     Meta-analyses                   |     4000 words    |     structured abstract of 400 words        |     no more than a combined total of seven tables and/or figures    |     4           |

## Genetic Epidemiology / GenE  {-}

[Instructions link here](https://onlinelibrary.wiley.com/page/journal/10982272/homepage/forauthors.html)


|     Type                     |     Format                          |     Keywords    |     Abstract    |
|------------------------------|-------------------------------------|-----------------|-----------------|
|     Research Articles        |     Free Format Submission          |     7           |     200         |
|     Reviews                  |                                     |                 |                 |
|     Letters to the Editor    |                                     |                 |                 |
|     Perspectives             |                                     |                 |                 |

## Journal of Epidemiology and Community Health / JECH {-}

[Instructions link here](https://jech.bmj.com/pages/authors/#submission_guidelines)

|     Type                                                  |     Word count          |     Abstract                                                              |     References             |     Table  or Illustration/Box    |
|-----------------------------------------------------------|-------------------------|---------------------------------------------------------------------------|----------------------------|-----------------------------------|
|     Editorial                                             |     up to 1200 words    |                                                                           |                            |     1                             |
|     Commentary                                            |     up to 800 words     |                                                                           |     up to 12 references    |                                   |
|     Original research                                     |     up to 3000 words    |     maximum of 250 words (Background, Methods, Results and Conclusion)    |     up to 40               |     up to 5                       |
|     Short   report                                        |     up to 1500 words    |     up to 200 words                                                       |     up to 20               |     up to 2                       |
|     Evidence-based public health policy   and practice    |     up to 3000 words    |     up to 250 words                                                       |     up to 40               |     5                             |
|     Theory and methods                                    |     up to 3000 words    |     up to 250 words                                                       |     up to 40               |     up to 5                       |
|     Essay                                                 |     up to 3000 words    |     up to 250 words                                                       |     up to 50               |     up to 5                       |
|     Glossary                                              |     up to 3000 words    |     should not exceed 150 words                                           |     up to 50               |                                   |
|     Debate                                                |     up to 1500 words    |     up to 150 words                                                       |     up to 15               |     1                             |
|     Research agenda                                       |     up to 1500 words    |     up to 150 words                                                       |     up to 30               |     up to 2                       |
|     Speakers' corner                                      |     up to 800 words     |                                                                           |     up to 10               |     0                             |
|     Gallery                                               |     up to 200 words     |                                                                           |                            |     1                             |
|     Letter                                                |     up to 400 words     |                                                                           |     up to 5                |     1                             |
|     Obituary                                              |     up to 250 words     |                                                                           |                            |     1                             |
|     Aphorism                                              |     up to 200 words     |                                                                           |     up to 5                |     1                             |
|     Supplements                                           |                         |                                                                           |                            |                                   |

## More subject area journals {-}

Not an exhaustive list:

- [Diabetes Epidemiology and Management](https://www.elsevier.com/journals/diabetes-epidemiology-and-management/2666-9706/guide-for-authors)
- [Sleep Epidemiology](https://www.elsevier.com/journals/sleep-epidemiology/2667-3436/guide-for-authors)
- [Social psychiatry and psychiatric epidemiology](https://www.springer.com/journal/127/submission-guidelines)


# Public Health Journals

## Public Health (PH) {-}

[Instructions link here](https://www.elsevier.com/journals/public-health/0033-3506/guide-for-authors)

| Article type                | Word length | Tables/figures | References | Peer reviewed |
|-----------------------------|-------------|----------------|------------|---------------|
| Original research           | 3000        | 5              | 100        | Yes           |
| Review article              | 3000        | 5              | 100        | Yes           |
| Short Communication         | 1500        | 1              | 10         | Yes           |
| Letter                      | 750         | 1              | 5          | No            |
| Celebrating Public Health Lives | 750    | 0              | 5          | No            |


# Others

##  Interdisciplinary {-}

### WIREs Computational Statistics / WCS {-}

[Instructions link here](https://wires.onlinelibrary.wiley.com/hub/about#ArticleCategories)

|    <br>Categories    	|    <br>Audience    	|    <br>Word counts     	|    <br>Figures + Tables    	|    <br>Pages    	|
|---	|---	|---	|---	|---	|
|    <br>Perspective    	|    <br>live debate    	|    <br>3,000    	|    <br>4    	|    <br>5    	|
|    <br>Primer    	|    <br>Meant for undergraduates    	|    <br>3,000    	|    <br>3    	|    <br>4    	|
|    <br>Overview    	|    <br>non-technical treatment of an important topic suitable for advanced   students    	|    <br>8,000    	|    <br>12    	|    <br>15    	|
|    <br>Advanced review    	|    <br>Aimed at advanced students     	|    <br>6,000    	|    <br>8    	|    <br>10    	|
|    <br>Systematic review    	|    <br>syntheses of peer-reviewed literature    	|    <br>6,000    	|    <br>8    	|    <br>10    	|
|    <br>Focus article    	|    <br>mini-reviews     	|    <br>4,000    	|    <br>6    	|    <br>6    	|
|    <br>Software focus    	|    <br>packages with high utility, review capabilities and how-to’s    	|    <br>3,000    	|    <br>3    	|    <br>4    	|
|    <br>Update    	|    <br>include new findings    	|    <br>Flexible    	|    <br>Flexible    	|    <br>Flexible    	|

<!---

I am not/less familiar with the following: 

- [Clinical Epidemiology](https://www.dovepress.com/clinical-epidemiology-journal): See Wiki about the publisher [Dove Medical Press](https://en.wikipedia.org/wiki/Dove_Medical_Press)
- [Epidemiologia](https://www.mdpi.com/journal/epidemiologia): See Wiki about the publisher [MDPI](https://en.wikipedia.org/wiki/MDPI)
- [Frontiers in Epidemiology](https://www.frontiersin.org/journals/epidemiology): See Wiki about the publisher [Frontiers Media](https://en.wikipedia.org/wiki/Frontiers_Media)
- [Cancer Epidemiology, Biomarkers & Prevention](https://aacrjournals.org/cebp): See Wiki about the publisher [AACR](https://en.wikipedia.org/wiki/American_Association_for_Cancer_Research)
---->

## International {-}

- [Journal of Epidemiology](https://jeaweb.jp/journal/): Japan Epidemiological Association
- [Epidemiology and Health](https://www.e-epih.org/): Korean Society of Epidemiology
- [Journal of Biostatistics and Epidemiology](https://jbe.tums.ac.ir/index.php/jbe): Tehran University of Medical Sciences
- [Epidemiology and Health System Journal](http://ijer.skums.ac.ir/): Shahrekord University of Medical Sciences
- [Iranian Journal of Epidemiology](https://irje.tums.ac.ir/en): Tehran University of Medical Sciences
- [Nepal Journal of Epidemiology](https://www.nepjol.info/index.php/NJE): Tribhuvan University Central Library
- [Journal of Preventive Epidemiology](https://jprevepi.com/): Society of Diabetic Nephropathy Prevention
- [Epidemiology and Society Health Review](http://journal2.uad.ac.id/index.php/eshr/index): Universitas Ahmad Dahlan
- [Journal of Interventional Epidemiology and Public Health](https://www.afenet-journal.net/#gsc.tab=0): African Field Epidemiology Network
- [International Journal of Epidemiology and Health Sciences](http://www.ijehs.com/): based in the Netherlands


Missing any interesting Epidemiology journal? [Let me know](https://ehsank.com/).